policies:
  - name: EmbeddingPolicy
    rnn_size: 64
    topic_rnn_size: 32
    embed_dim: 20
    sparse_attention: False
    batch_size: [8, 16]
    epochs: 500
    attn_shift_range: 5
    attn_before_rnn: True
    attn_after_rnn: True
    skip_time: False
    use_topics: True